### ISSUE TITLE
Перевод режима демона на daemonize

### ISSUE THREAD

**Issue by NCrashed** [DSoftOut/pgator#101]
Будет касаться только демона, использовать [daemonize](https://github.com/NCrashed/daemonize)

**Comment by denizzzka** [comment]
Предлагаю вообще выпилить демонизацию полностью. Нет в ней смысла - systemd и аналоги делают это лучше.

**Comment by NCrashed** [comment]
Ну тогда просто не трогать, текущая схема вполне рабочая.

9 февраля 2015 г., 7:47 пользователь denizzzka <notifications@github.com>
написал:

**Comment by denizzzka** [comment]
да, а если сломается что-то то тупо выпилить и всё. Тикет закрыть можно, наверно.
