### ISSUE TITLE
Для второго statement не обрабатываются ошибки

### ISSUE THREAD

**Issue by denizzzka** [DSoftOut/pgator#124]
вызов заведомо ошибочного (во второй строке) кода метода:
```sql
{"select 1 as c1","2 as c2;"}
```
приводит к рестарту (с записью об этом в логе), но без какого-либо сообщения об ошибке синтаксиса

**Comment by NCrashed** [comment]
Потому что до второго он и не доходит, а проверка идет уже на стороне постгреса.

**Comment by denizzzka** [comment]
Не понял, а почему до второго не доходит?

**Comment by NCrashed** [comment]
Происходит ошибка обработки первого запроса => транзакция признается ошибочной и завершается. Чтобы реализовать хотя бы синтаксическую проверку всех запросов, то нужно переходить полностью на prepared statement. Тогда ошибки вывалятся при регистрации prepared statement, т.е. при загрузке в pgator нового сервера.

**Comment by denizzzka** [comment]
первый запрос, вроде, нормальный?

**Comment by NCrashed** [comment]
Понял в чем проблема, буду фиксить.
