### ISSUE TITLE
в логе вместо null для значений параметров показывается ""

### ISSUE THREAD

**Issue by denizzzka** [DSoftOut/pgator#128]
пример (второй параметр IS NULL):
With params: ["2354877787627192443", "", "1"]

(кмк, идеально было бы использовать для хранения значений аргументов std.typecons: Nullable - тогда такие ошибки сразу повылезут)

**Comment by NCrashed** [comment]
Со стороны D строковый литерал `null` эквивалентен `""`. Nullable и так использую, но в большинстве уже на стороне тестового клиента и глубоко в бекэнде. По середине проходят бсоны со строками.

**Comment by denizzzka** [comment]
но ведь "" который length == 0 и NULL в SQL это разные вещи... и, собственно, "" эти выглядят как пустая строка

**Comment by NCrashed** [comment]
И встает проблема на стороне D, у него (по понятным причинам) `"" == null` и `"".length == (cast(string)null).length`

**Comment by NCrashed** [comment]
И в `libpq` я могу различить `NULL` и `""` только по вызову специальной функции, т.к. в байтовом протоколе они все имеют размер 0 байт.

**Comment by NCrashed** [comment]
Хм, полагаться на различие `NULL` и `""` в проектировании, наверняка плохой паттерн.

**Comment by denizzzka** [comment]
наоборот!

> И встает проблема на стороне D, у него (по понятным причинам) "" == null и "".length == (cast(string)null).length

это и лечит Nullable же

**Comment by NCrashed** [comment]
Лечится, но требует сильного изменения публичного API, сейчас оно правильно различает `""` и `null` при конвертации в BSON. Но внутри логгирования (а это потребует переписывания десериализатора) внедрение Nullable будет явно оверкиллом, оно печатает `[string]` и видит один из членов равным `null`, ну и конвертит по стандартам D в `""`.

**Comment by NCrashed** [comment]
Итого при хранении все верно, внутри есть спец тип `BSON.Type._null` и в JSON попадает все правильно.

**Comment by NCrashed** [comment]
На самом деле не представляю как оно проходит через параметры, сохраняя при этом различие `null` и `""` ^^

**Comment by denizzzka** [comment]
> На самом деле не представляю как оно проходит через параметры, сохраняя при этом различие null и "" ^^

оно - что? postgresq по-моему, отдельную битовую матрицу нулей в ячейках возвращает

**Comment by NCrashed** [comment]
Да я про `pgator`, при считывания из JSON в строку для пересылки постгресу
инфа о разности null и "" должна теряться. Однако тесты прекрасно проходит.

3 марта 2015 г., 4:17 пользователь denizzzka <notifications@github.com>
написал:

**Comment by denizzzka** [comment]
в строку оно с кавычками, может, считывается?

**Comment by NCrashed** [comment]
Эту версию еще нужно проверить, но точно помню, что из json "" и null при проверке одинаковые как значения.

**Comment by denizzzka** [comment]
стандарт json в себе ведь имеет null - полный аналог SQL NULL, как я понимаю. Значит, авторы библиотеки тоже должны были реализовать где-то хранения флага "занулённости".

**Comment by denizzzka** [comment]
не актуально: в новой версии все логи по-другому (возможно, придётся повторно пройти по некоторым граблям с логами)
