### ISSUE TITLE
wish: переключаемый "поворот" таблицы

### ISSUE THREAD

**Issue by denizzzka** [DSoftOut/pgator#140]
Сейчас таблица отдаётся в JSON "поколоночно":
```json
 {"колонка":["значение",...], "колонка2":["значение", ...], ...}
```

Идея состоит в том, чтобы добавить ещё вывод "построчно", в виде кортежа:
```json
 [{"колонка":"значение", "колонка2":"значение"}, {"колонка":"значение", "колонка2":"значение"}, ...}
```

и построчно в виде массива:
```json
 [["колонка","колонка2"],[значение, значение2],[значение, значение2],...]
```

(Это всё аналоги selectcol_arrayref, selectall_hashref, selectall_arrayref из DBI)

Переключение сделать отдельным полем в настройках в таблице методов.

По опыту эксплуатации оказалось, что иногда это было бы очень удобно.

**Comment by kergma** [comment]
> Переключение сделать отдельным полем в настройках в таблице методов.

это плохая идея, лучше формат выдачи результата задавать непосредственно в запросе, например 
```
{
"jsonrpc":"2.0",
"method":"generate_id",
"params":[],
"format":"bycolumn" ("byrow-hashes", "byrow-arrays", "onerow-hash" и т. п. )
}
```

**Comment by denizzzka** [comment]
стандарту JSON-RPC не соответствует это

**Comment by kergma** [comment]
отчего же не соответствует ? там написано, какие поля должны быть в запросе (jsonrpc, method, params, id) но ничего не сказано что не может быть других полей

**Comment by kergma** [comment]
никакой путаницы - веб-программист сам решает, в каком виде ему нужен результат, и указывает непосредственно в месте вызова, все прозрачно, ничего не размазано по разным местам, и нет необходимости a) делать еще одно поле в jsonrpc б) делать идентичные методы с разными форматами выдачи (если таковые нужны)

**Comment by denizzzka** [comment]
> никакой путаницы - веб-программист сам решает, в каком виде ему нужен результат

мне кажется, в этом и может быть проблема. во-1, путаница определённая может происходить, если где-то будет забыт "поворачивающий" флаг

во-2 это раскрывает инфомрацию о бэкенде, что может быть критичным, если апи торчит наружу

в-3 проксирование JSON-RPC может потерять нестандартные флаги (не знаю, бывает ли оно на этом уровне абстракции, но ничто не мешает, вроде)

**Comment by kergma** [comment]
>забыт "поворачивающий" флаг

он не может забыть флаг - он же сам решает как он хочет видеть результат, а если там не то, что он ожидал - то идет и правит свой вызов, без всякого взаимодействия с программистом бакенда

>раскрывает инфомрацию о бэкенде

не совсем понял, что может быть раскрыто и каким образом

>проксирование JSON-RPC может потерять нестандартные флаги

это да, но это просто означает что в таких случаях нужно подбирать нетеряющие прокси

**Comment by denizzzka** [comment]
подмывает сделать и так и так чтобы было, настраиваемо в конфиг-файле...

**Comment by denizzzka** [comment]
сделано в новой ветке
