### ISSUE TITLE
username перестал выставляться там, где это нужно

### ISSUE THREAD

**Issue by denizzzka** [DSoftOut/pgator#143]
username перестал выставляться там, где это нужно по настройке set_username

в результате прилетает ошибка типа:

```json
[2015-12-28 17:43:56,148] DEBUG - JSON >>>>>>> {"jsonrpc": "2.0", "params": ["лоты", [{"eq": "Электронный аукцион", "key": "стадия_text"}], [{"наименование_торгов": "asc"}, "лот"], "0", "0"], "method": "data.browse", "id": "1706-7c36124a-2f42-4fef-9e8d-1f8723935a41"}
[2015-12-28 17:43:56,148] DEBUG - <<<<<<<<<<<< {
    "jsonrpc": "2.0",
    "id": "1706-7c36124a-2f42-4fef-9e8d-1f8723935a41",
    "error": {
        "message": "Server error. ERROR:  unrecognized configuration parameter \"pgator.username\"\nCONTEXT:  PL/pgSQL function sys.\"user\"() line 3 at RETURN\n",
        "code": -32000
    }
```

~~И ещё этот странный код, который в обоих случаях делает то же самое, похоже:~~

~~https://github.com/DSoftOut/pgator/blob/bb79a8ebfe3a40366b28b043050397bbeb48a555/source/server/database.d#L230~~

Алсо, надо добавить в интеграционные тесты проверку выставления пользовательского имени-пароля.

**Comment by denizzzka** [comment]
там далее внутри extremeDirtyHuckRunInSeparateThreadPleaseRedoneThis() вызов, кажется, всегда с null вместо auth-данных

**Comment by NCrashed** [comment]
Проверим, возможно и последний фикс был виноват.

**Comment by denizzzka** [comment]
https://github.com/DSoftOut/pgator/compare/fix_%23143?expand=1
