### ISSUE TITLE
wish: перейти на prepared statements?

### ISSUE THREAD

**Issue by denizzzka** [DSoftOut/pgator#48]
(кажется, когда планы и ТЗ только обсуждали это всплывало, или нет?)

Подробности о prepared statements тут:
http://www.postgresql.org/docs/current/static/sql-prepare.html

Вызовы тогда выглядят так. Сначала грузим всю таблицу в постгрес:

PREPARE fooplan (int, text, bool, numeric) AS -- автоматически добавлять, "fooplan" это название, можно делать "УникальныйПрефиксИмяМетода"
INSERT INTO foo VALUES($1, $2, $3, $4); -- запрос из sql_queries[]

А сам вызов делается так:

EXECUTE fooplan(1, 'Hunter Valley', 't', 200.00);

Предполагаемые преимущества:

- проверка синтаксиса будет происходить в момент загрузки таблицы json_rpc а не во время вызова метода пользователем
- увеличится скорость выполнения запросов
- необязательное: можно будет заранее для аргументов указывать конкретные типы в таблице json_rpc. Побочка: можно будет показывать их прикладным программистам специальным методом в красивом виде (наша практика показала что удобно иметь метод, который возвращает из json_rpc список всех методов системы с количеством аргументов и каментами - можно это даже в документацию будет внести)

Кто что думает?

**Comment by denizzzka** [comment]
Что нужно сделать чтобы запилить это? Просто берём и пилим или какая-то подготовка предварительная в коде требуется?

Имею желание заняться на досуге

**Comment by NCrashed** [comment]
Препятствий для запила нет, кроме изменения в работе пула. Сначала регистрировать методы, при выходе их дропать, изменение внутренних вызовов libpq.

**Comment by denizzzka** [comment]
> Когда при загрузке будет проверяться синтаксис то строки таблицы, где обнаружен неправильный синтаксис нужно пропускать, с выводом в лог соответствующего сообщения.

Это при перечитывании конфигурации.

А при первоначальном запуске в таком случае пусть по умолчанию запуск pgator прерывается с ошибкой, если в конфиге не указана соответствующая опция.

**Comment by denizzzka** [comment]
сделано в новой ветке
