### ISSUE TITLE
bug: строка аргумента "null" воспринимается как NULL, а не как текст

### ISSUE THREAD

**Issue by denizzzka** [DSoftOut/pgator#77]
(чтоб не забыть, после #75 осталось)

**Comment by NCrashed** [comment]
Баг не воспроизводится, `select 'null'::text as null_test_value;` правильно обрабатывается как строка.

**Comment by denizzzka** [comment]
не не, аргумент "null" из JSON надо передать в:

select $1::text

получится NULL вместо "null"

**Comment by denizzzka** [comment]
не пофиксилось! запрос:
```json
{
	"jsonrpc": "2.0",
	"method": "test.echo",
	"params": [ null ],
	"id": 1
}
```

в эхометод:
```sql
{"select $1::text as passed_value, $1 IS NULL as isNull"}
```

возвращает:
```json
{
	"id": 1,
	"result": {
		"isnull": false,
		"passed_value": ""
	},
	"jsonrpc": "2.0"
}
```

**Comment by denizzzka** [comment]
(было бы здорово добавить это в тест)

**Comment by NCrashed** [comment]
Хм, я добавил этот тест в клиент и мне приходит правильный ответ:
```
{"result":{"isnull":[true],"passed_value":[null]},"jsonrpc":"2.0","id":1469432499}
```

**Comment by NCrashed** [comment]
Текущая версия `v0.2.1-a8a90b0`

**Comment by denizzzka** [comment]
работает на этой:
0.2.1+commit.3.ge5e3773
commit e5e37736a01ae734b07fb5dfec65eb85ca286dbe
Author: Anton Gushcha <ncrashed@gmail.com>
Date:   Fri Feb 27 18:44:08 2015 +0300

    Another test to check #77

ещё может быть бэкенд был другой версии (старый позволялся, обновил принудительно)
